[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = """function Card:get_chip_mult()
    if self.debuff then return 0 end
    if self.ability.set == 'Joker' then return 0 end
    if self.ability.effect == "Lucky Card" then 
        if pseudorandom('lucky_mult') < G.GAME.probabilities.normal/5 then
            self.lucky_trigger = true
            return self.ability.mult
        else
            return 0
        end
    else  
        return self.ability.mult
    end
end"""





position = "at"







payload = """function Card:get_chip_mult()
    if #SMODS.find_card('j_bbb_emme_joker') < 1 then
        if self.debuff then return 0 end
        if self.ability.set == 'Joker' then return 0 end
        if self.ability.effect == "Lucky Card" then 
            if pseudorandom('lucky_mult') < G.GAME.probabilities.normal/5 then
                self.lucky_trigger = true
                return self.ability.mult
            else
                return 0
            end
        else  
            return self.ability.mult
        end
    elseif #SMODS.find_card('j_bbb_emme_joker') >= 1 and self.ability.effect == "Lucky Card" then
        self.lucky_trigger = true
        return 20
    else
        return self.ability.mult
    end
end"""
match_indent = true